###############
#TEMPLATE ONLY#
###############
version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier
    logging:
        driver: syslog
        options:
            syslog-address: "tcp://localhost:8089"
            
    app:
        image: harisshafiq09/sample-app:latest
        container_name: app
        command: /var/sample-app
        ports:
            - 8083:8083
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:8089"
        networks:
          - elknetwork            
